language: java
notifications:
  email: false
  slack: fraud-detectiona1:CLY2fRWtKwE8jynlCTLN259c
script:
- mvn validate
- mvn compile
- mvn test
- mvn package
- mvn verify
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.organization=fraud-detection \ -Dsonar.host.url=https://sonarcloud.io \ -Dsonar.login=3594c4fef2508b9219fb9927ed3fef8237d490f3